source 'http://github.intra.douban.com/iOS/CocoaPodsSpecs.git'
source 'http://github.intra.douban.com/mirror/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'MTURLProtocol_Example' do
  pod 'MTURLProtocol',                                    :path => '../'
  target 'MTURLProtocol_Tests' do
    inherit! :search_paths
  end
end

post_install do | installer |
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
